blank_issues_enabled: true
contact_links:
  - name: Nice
    url: https://t.me/Nice_xD
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: 
    about: Documentation for getting started with bot.
